name: pboproject
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar_v2: ^4.2.8
  cupertino_icons: ^1.0.2
  app_links: ^3.4.3

  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #akuntansi
    - images/akuntansi/akuntansi1.png
    - images/akuntansi/akuntansi2.png
    - images/akuntansi/akuntansi3.png
    - images/akuntansi/akuntansi4.png
    - images/akuntansi/akuntansi5.png
    - images/akuntansi/akuntansi6.png
  #manajemen
    - images/manajemen/m1.png
    - images/manajemen/m2.png
    - images/manajemen/m3.png
    - images/manajemen/m4.png
    - images/manajemen/m5.png
    - images/manajemen/m6.png
    - images/manajemen/m7.png
    - images/manajemen/m8.png
    - images/manajemen/m9.png
  #sisteminformasi
    - images/si/s1.png
    - images/si/s2.png
    - images/si/s3.png
    - images/si/s4.png
    - images/si/s5.png
    - images/si/s6.png
    - images/si/s7.png
    - images/si/s8.png
  #sample
    - images/cv1.png
    - images/cv2.png
    - images/cv4.png
    - images/cvro4.png
    - images/cv7.png
    - images/cv8.png
    - images/cv3d1.png
    - images/cv3d2.png
    - images/cvro1.png
    - images/cvro2.png
    - images/cvro3.png
    - images/empty.png
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.otf
        - asset: fonts/Poppins-Bold.otf
          weight: 600
        - asset: fonts/Poppins-Medium.otf
        - asset: fonts/Poppins-Regular.otf
